config/routes.rb
Rails.application.routes.draw do

  resources :artists, shallow: true do
    resources :songs, except: [:index]
  end
  resources :songs, only: [:index]
  resources :playlists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates_presence_of :name

  has_many :songs
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_songs # Must be first
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ApplicationRecord
  validates_presence_of :title, :length, :play_count
  belongs_to :artist
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    session[:secret] = "This time for real, though."
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.create(artist_params)
    if @artist.save
      redirect_to '/artists'
    else
      render :new
    end
  end

  private

    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/songs_controller.rb
class SongsController <ApplicationController

  def index
    @songs = Song.all
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @song = Song.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.create(song_params)
    if @song.save
      redirect_to "/songs"
    else
      render :new
    end
  end

    private
      def song_params
        params.require(:song).permit(:title, :length, :play_count, :artist_id)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/index.html.erb
<header>
  <%= link_to "Add New Artist", new_artist_path %>
</header>

<%= @artists.each do |artist| %>
  <p><%= artist.name %></p>
<% end %>

app/views/artists/new.html.erb
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<h1>Artist: <%= @artist.name %> </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBox1804</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/index.html.erb
<html>
  <head>
    <link rel="stylesheets" href="reset.css">
    <link rel="stylesheets" href="songs.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Shrikhand" rel="stylesheets">
    <title>Songs</title>
  </head>
  <body>
    <div class= "header">
      <h1>Songs</h1>
    </div>
    <div class= "songs-container">
        <% @songs.each do |song| %>
        <div class="song-items">
          <ul>
            <li><img src="/assets/vinyl.jpg" alt="record"></li>
            <li><%= song.title %></li>
            <li><%= song.length %> seconds</li>
            <li>Play Count: <%= song.play_count %></li>
          </ul>
        </div>
        <% end %>
    </div>
</body>
</html>

app/views/songs/new.html.erb
<html>
  <head>
    <link rel="stylesheets" href="reset.css">
    <link rel="stylesheets" href="form.css">
    <link href="https://fonts.googleapis.com/css?family=Economica|Knewave" rel="stylesheets">
    <title>Add Song</title>
  </head>
  <body>
    <div id="top-header">
      <h1>Create A New Song</h1>
    </div>

    <%= form_for [@artist, @song] do |f| %>
    <div class="container">

    <div class="row">
      <%= f.label :title, class:'label' %>
      <%= f.text_field :title, class:'text-box'%>
    </div>

    <div class="row">
      <%= f.label :length, class:'label' %>
      <%= f.text_field :length, class:'text-box' %>
    </div>

    <div class="row">
      <%= f.label :play_count, class:'label' %>
      <%= f.text_field :play_count, class:'text-box' %>
    </div>

    <div class="row">
      <%= f.submit class: 'button'%>
    </div>
    <% end %>
  </div>
</body>
</html>